# Add 'feature' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
enhancement:
  - head-branch: ["^feat", "^new", "^enhance"]
  - description: "New feature or request"
  - color: "a2eeef"

documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"
  - head-branch: ["^doc"]
  - description: "Change to documentation"
  - color: "0e8a16"

bug: 
  - head-branch: ['^fix', '^bug']
  - description: "Something went wrong"
  - color: "d73a4a"

maintenance: 
  - head-branch: ['^chore', '^maint', '^noop', '^no-op', '^upkeep', '^dev']
  - description: "Non-behavior related change"
  - color: "e99695"

dependencies: 
  - head-branch: ['^deps', '^dependencies']
  - description: "Pull requests that update a dependency file"
  - color: "0366d6"

devops:
  - changed-files:
    - any-glob-to-any-file: [".github/**", ".vscode/**"]
  - description: "Change to development workflows"
  - color: "9B3864"
