name: Auto Merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

permissions:
  contents: write   # Required for merging the PR
  pull-requests: write  # Required for managing pull requests

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto-Merge for Dependabot PR
        if: github.actor == 'dependabot[bot]' || github.event_name == 'workflow_dispatch'
        run: gh pr merge ${{ github.event.pull_request.number }} --auto --squash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}