name: Labeler
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Dump GitHub refs
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: echo "$HEAD_REF"

      - name: Label
        id: label
        uses: athackst/labeler@feature/label-metadata

      - name: Debug labels
        env:
          ALL_LABELS: ${{ steps.label.outputs.all-labels }}
        run: echo $ALL_LABELS
        
