name: PR Labeler
on:
  pull_request_target:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Label
        uses: actions/labeler@v5
