name: publish_docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup config
        uses: athackst/athackst.mkdocs@main
      - name: MkDocs Simple action
        uses: athackst/mkdocs-simple-plugin@main
