name: Docs

on:
  push:
    branches: [master]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: MkDocs Simple action
        uses: athackst/mkdocs-simple-plugin@v0.1.0
