name: Docs

on:
  push:
    branches: [master]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: MkDocs Simple action
        uses: athackst/mkdocs-simple-plugin@workflows/test-action
