name: publish_docs

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup config
        run: |
          wget https://github.com/athackst/athackst.github.io/archive/mkdocs.zip -O temp.zip
          unzip temp.zip
          mv athackst.github.io-mkdocs/* .
          rm temp.zip
          cat mkdocs.yml
      - name: MkDocs Simple action
        uses: athackst/mkdocs-simple-plugin@v0.1.2
        env:
          REPO_URL: http://github.com/${{ github.repository }} 
          SITE_NAME: ${{ github.repository }}
          SITE_URL: http://athackst.github.io/${{ github.event.repository.name }}
