name: test

on:
  workflow_dispatch:
  pull_request:


jobs:
  dotfiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install dotfiles
        run: |
          ./install.sh

  test-site:
    permissions:
      contents: read
    uses: athackst/ci/.github/workflows/mkdocs_site.yml@main
    with:
      pages: false
    secrets: inherit

  complete:
    needs:
      - dotfiles
      - test-site
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: echo "Completed successfully!"
